const userData = [
  {
    id: 0,
    username: "doni_doni",
    name: "정형돈",
    imgUrl: "image/feeds/doni.jpg",
    storyActive: true,
    friend: true,
  },
  {
    id: 1,
    username: "wecode_bootcamp",
    name: ">wecode | 위코드",
    imgUrl: "image/feeds/wecode1.jpg",
    storyActive: false,
    friend: true,
  },
  {
    id: 2,
    username: "wecode_founder",
    name: "송은우 (Eun Woo Song)",
    imgUrl: "image/feeds/wecode2.jpg",
    storyActive: false,
    friend: true,
  },
  {
    id: 3,
    username: "wecode_korea",
    name: "",
    imgUrl: "image/default_profile.jpg",
    storyActive: false,
    friend: true,
  },
  {
    id: 4,
    username: "wecode_socialclub",
    name: ">wecode | 위코드 소셜클럽",
    imgUrl: "image/feeds/wecode3.jpg",
    storyActive: false,
    friend: true,
  },
  {
    id: 5,
    username: "wecodedk",
    name: "WeCode",
    imgUrl: "image/feeds/wecode4.jpg",
    storyActive: false,
    friend: true,
  },
  {
    id: 6,
    username: "cristiano",
    name: "호날두",
    imgUrl: "image/feeds/ronaldo.jpg",
    storyActive: true,
    friend: true,
  },
  {
    id: 7,
    username: "great_park",
    name: "박명수",
    imgUrl: "image/feeds/park.png",
    storyActive: true,
    friend: true,
  },
  {
    id: 8,
    username: "haha_pd",
    name: "하하",
    imgUrl: "image/feeds/haha.jpg",
    storyActive: true,
    friend: true,
  },
  {
    id: 9,
    username: "gil_gil",
    name: "길",
    imgUrl: "image/feeds/gil.jpeg",
    storyActive: true,
    friend: true,
  },
  {
    id: 10,
    username: "jaeseok_god",
    name: "유재석",
    imgUrl: "image/feeds/god.png",
    storyActive: true,
    friend: true,
  },
  {
    id: 11,
    username: "juna_nana",
    name: "정준하",
    imgUrl: "image/feeds/juna.jpeg",
    storyActive: true,
    friend: true,
  },
  {
    id: 12,
    username: "hong_hong",
    name: "노홍철",
    imgUrl: "image/feeds/hongcheol.png",
    storyActive: true,
    friend: true,
  },
  {
    id: 13,
    username: "hwang_gwang",
    name: "황광희",
    imgUrl: "image/side_profile/hwang.png",
    storyActive: false,
    friend: false,
  },
  {
    id: 14,
    username: "jojo_seho",
    name: "조세호",
    imgUrl: "image/side_profile/jojo.png",
    storyActive: false,
  },
  {
    id: 15,
    username: "front_jeon",
    name: "",
    imgUrl: "image/side_profile/front.jpeg",
    storyActive: false,
    friend: false,
  },
  {
    id: 16,
    username: "pooconi_free",
    name: "데프콘",
    imgUrl: "image/side_profile/pooconi.jpg",
    storyActive: false,
    friend: false,
  },
  {
    id: 17,
    username: "jeong_ok12",
    name: "정승옥",
    imgUrl: "image/default_profile.jpg",
    email: "vsnm25@naver.com",
    password: "123456",
    storyActive: false,
  },
];

export default userData;
